version: '3'
services:
  mysql:
    build:
      dockerfile: Dockerfile
      context: ./mysql
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: some_secret
      MYSQL_USER: mysql_user
      MYSQL_PASSWORD: some_secret
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - '10080:80'
  api:
    build:
      dockerfile: Dockerfile.dev
      context: ./api
    volumes:
      - /app/node_modules
      - ./api:/app
    environment:
      - JWT_SECRET=averylongjwtsecretisgood
      - JWT_ISSUER=my.website.com
      - MYSQL_HOST=mysql
      - MYSQL_DATABASE=appWithAPIdb
      - MYSQL_USER=mysql_user
      - MYSQL_PASSWORD=some_secret
  app:
    build:
      dockerfile: Dockerfile.dev
      context: ./app
    volumes:
      - /app/node_modules
      - ./app:/app
